[package]
name = "test-fieldnotes"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
futures = "0.3"
reqwest = { version = "0.11", features = ["json", "cookies"] }
thiserror = "1.0"
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
